java.lang.ArrayIndexOutOfBoundsException: 10 
After the catch statement 